---
notificationEmbed:
  red: 0
  green: 255
  blue: 0
  title: "New Notification - %notification%"
  thumbnail: ""
  description: ""
  fields:
  - title: "URL"
    content: "%url%"
    inline: true
  buttons: []
