---
MYSQL:
  select: "SELECT * FROM %table% WHERE %placeholder% %order% %limit%"
  selectAll: "SELECT * FROM %table% WHERE 1"
  update: "UPDATE %table% SET %placeholder% WHERE id=?"
  insert: "INSERT INTO %table% (%placeholder-1%) VALUES(%placeholder-2%)"
  createTable: "CREATE TABLE IF NOT EXISTS %table% (%placeholder%, PRIMARY KEY(%keys%))"
  delete: "DELETE FROM %table% WHERE id=?"
  dataTypes:
    dev.lightdream.originalpanel.dto.data.UnbanData$UnbanDecision: "TEXT"
    dev.lightdream.originalpanel.dto.data.ComplainData$ComplainStatus: "TEXT"
    java.lang.Integer: "INT"
    dev.lightdream.originalpanel.dto.data.UnbanData$UnbanStatus: "TEXT"
    long: "BIGINT"
    dev.lightdream.originalpanel.dto.data.ApplyData$ApplyDecision: "TEXT"
    dev.lightdream.originalpanel.dto.data.ApplyData$ApplyStatus: "TEXT"
    int: "INT"
    java.util.UUID: "TEXT"
    dev.lightdream.originalpanel.dto.data.BugsData$BugStatus: "TEXT"
    java.lang.String: "TEXT"
    double: "DOUBLE"
    java.lang.Double: "DOUBLE"
    java.lang.Long: "BIGINT"
    boolean: "BOOLEAN"
    dev.lightdream.originalpanel.dto.data.ComplainData$ComplainDecision: "TEXT"
    java.lang.Float: "FLOAT"
    java.lang.Boolean: "BOOLEAN"
    float: "FLOAT"
  autoIncrement: "AUTO_INCREMENT"
  orderDesc: "ORDER BY %order% DESC"
  orderAsc: "ORDER BY %order% ASC"
  limit: "LIMIT %limit%"
MARIADB:
  select: "SELECT * FROM %table% WHERE %placeholder%"
  selectAll: "SELECT * FROM %table% WHERE 1"
  update: "UPDATE %table% SET %placeholder% WHERE id=?"
  insert: "INSERT INTO %table% (%placeholder-1%) VALUES(%placeholder-2%)"
  createTable: "CREATE TABLE IF NOT EXISTS %table% (%placeholder%, PRIMARY KEY(%keys%))"
  delete: "DELETE FROM %table% WHERE id=?"
  dataTypes:
    dev.lightdream.originalpanel.dto.data.UnbanData$UnbanDecision: "TEXT"
    dev.lightdream.originalpanel.dto.data.ComplainData$ComplainStatus: "TEXT"
    java.lang.Integer: "INT"
    dev.lightdream.originalpanel.dto.data.UnbanData$UnbanStatus: "TEXT"
    long: "BIGINT"
    dev.lightdream.originalpanel.dto.data.ApplyData$ApplyDecision: "TEXT"
    dev.lightdream.originalpanel.dto.data.ApplyData$ApplyStatus: "TEXT"
    int: "INT"
    java.util.UUID: "TEXT"
    dev.lightdream.originalpanel.dto.data.BugsData$BugStatus: "TEXT"
    java.lang.String: "TEXT"
    double: "DOUBLE"
    java.lang.Double: "DOUBLE"
    java.lang.Long: "BIGINT"
    boolean: "BOOLEAN"
    dev.lightdream.originalpanel.dto.data.ComplainData$ComplainDecision: "TEXT"
    java.lang.Float: "FLOAT"
    java.lang.Boolean: "BOOLEAN"
    float: "FLOAT"
  autoIncrement: "AUTO_INCREMENT"
  orderDesc: "ORDER BY %order% DESC"
  orderAsc: "ORDER BY %order% ASC"
  limit: "LIMIT %limit%"
SQLSERVER:
  select: "SELECT * FROM %table% WHERE %placeholder%"
  selectAll: "SELECT * FROM %table% WHERE 1"
  update: "UPDATE %table% SET %placeholder% WHERE id=?"
  insert: "INSERT INTO %table% (%placeholder-1%) VALUES(%placeholder-2%)"
  createTable: "CREATE TABLE IF NOT EXISTS %table% (%placeholder%, PRIMARY KEY(%keys%))"
  delete: "DELETE FROM %table% WHERE id=?"
  dataTypes:
    dev.lightdream.originalpanel.dto.data.UnbanData$UnbanDecision: "TEXT"
    dev.lightdream.originalpanel.dto.data.ComplainData$ComplainStatus: "TEXT"
    java.lang.Integer: "INT"
    dev.lightdream.originalpanel.dto.data.UnbanData$UnbanStatus: "TEXT"
    long: "BIGINT"
    dev.lightdream.originalpanel.dto.data.ApplyData$ApplyDecision: "TEXT"
    dev.lightdream.originalpanel.dto.data.ApplyData$ApplyStatus: "TEXT"
    int: "INT"
    java.util.UUID: "TEXT"
    dev.lightdream.originalpanel.dto.data.BugsData$BugStatus: "TEXT"
    java.lang.String: "TEXT"
    double: "DOUBLE"
    java.lang.Double: "DOUBLE"
    java.lang.Long: "BIGINT"
    boolean: "BOOLEAN"
    dev.lightdream.originalpanel.dto.data.ComplainData$ComplainDecision: "TEXT"
    java.lang.Float: "FLOAT"
    java.lang.Boolean: "BOOLEAN"
    float: "FLOAT"
  autoIncrement: "AUTO_INCREMENT"
  orderDesc: "ORDER BY %order% DESC"
  orderAsc: "ORDER BY %order% ASC"
  limit: "LIMIT %limit%"
POSTGRESQL:
  select: "SELECT * FROM %table% WHERE %placeholder%"
  selectAll: "SELECT * FROM %table% WHERE 1"
  update: "UPDATE %table% SET %placeholder% WHERE id=?"
  insert: "INSERT INTO %table% (%placeholder-1%) VALUES(%placeholder-2%)"
  createTable: "CREATE TABLE IF NOT EXISTS %table% (%placeholder%, PRIMARY KEY(%keys%))"
  delete: "DELETE FROM %table% WHERE id=?"
  dataTypes:
    dev.lightdream.originalpanel.dto.data.UnbanData$UnbanDecision: "TEXT"
    dev.lightdream.originalpanel.dto.data.ComplainData$ComplainStatus: "TEXT"
    java.lang.Integer: "INT"
    dev.lightdream.originalpanel.dto.data.UnbanData$UnbanStatus: "TEXT"
    long: "BIGINT"
    dev.lightdream.originalpanel.dto.data.ApplyData$ApplyDecision: "TEXT"
    dev.lightdream.originalpanel.dto.data.ApplyData$ApplyStatus: "TEXT"
    int: "INT"
    java.util.UUID: "TEXT"
    dev.lightdream.originalpanel.dto.data.BugsData$BugStatus: "TEXT"
    java.lang.String: "TEXT"
    double: "DOUBLE"
    java.lang.Double: "DOUBLE"
    java.lang.Long: "BIGINT"
    boolean: "BOOLEAN"
    dev.lightdream.originalpanel.dto.data.ComplainData$ComplainDecision: "TEXT"
    java.lang.Float: "FLOAT"
    java.lang.Boolean: "BOOLEAN"
    float: "FLOAT"
  autoIncrement: "AUTO_INCREMENT"
  orderDesc: "ORDER BY %order% DESC"
  orderAsc: "ORDER BY %order% ASC"
  limit: "LIMIT %limit%"
H2:
  select: "SELECT * FROM %table% WHERE %placeholder%"
  selectAll: "SELECT * FROM %table% WHERE 1"
  update: "UPDATE %table% SET %placeholder% WHERE id=?"
  insert: "INSERT INTO %table% (%placeholder-1%) VALUES(%placeholder-2%)"
  createTable: "CREATE TABLE IF NOT EXISTS %table% (%placeholder%, PRIMARY KEY(%keys%))"
  delete: "DELETE FROM %table% WHERE id=?"
  dataTypes:
    dev.lightdream.originalpanel.dto.data.UnbanData$UnbanDecision: "TEXT"
    dev.lightdream.originalpanel.dto.data.ComplainData$ComplainStatus: "TEXT"
    java.lang.Integer: "INT"
    dev.lightdream.originalpanel.dto.data.UnbanData$UnbanStatus: "TEXT"
    long: "BIGINT"
    dev.lightdream.originalpanel.dto.data.ApplyData$ApplyDecision: "TEXT"
    dev.lightdream.originalpanel.dto.data.ApplyData$ApplyStatus: "TEXT"
    int: "INT"
    java.util.UUID: "TEXT"
    dev.lightdream.originalpanel.dto.data.BugsData$BugStatus: "TEXT"
    java.lang.String: "TEXT"
    double: "DOUBLE"
    java.lang.Double: "DOUBLE"
    java.lang.Long: "BIGINT"
    boolean: "BOOLEAN"
    dev.lightdream.originalpanel.dto.data.ComplainData$ComplainDecision: "TEXT"
    java.lang.Float: "FLOAT"
    java.lang.Boolean: "BOOLEAN"
    float: "FLOAT"
  autoIncrement: "AUTO_INCREMENT"
  orderDesc: "ORDER BY %order% DESC"
  orderAsc: "ORDER BY %order% ASC"
  limit: "LIMIT %limit%"
SQLITE:
  select: "SELECT * FROM %table% WHERE %placeholder% %order% %limit%"
  selectAll: "SELECT * FROM %table% WHERE 1"
  update: "UPDATE %table% SET %placeholder% WHERE id=?"
  insert: "INSERT INTO %table% (%placeholder-1%) VALUES(%placeholder-2%)"
  createTable: "CREATE TABLE IF NOT EXISTS %table% (%placeholder%)"
  delete: "DELETE FROM %table% WHERE id=?"
  dataTypes:
    java.util.UUID: "TEXT"
    java.lang.Integer: "INTEGER"
    java.lang.String: "TEXT"
    long: "BIGINT"
    double: "REAL"
    java.lang.Double: "REAL"
    java.lang.Long: "BIGINT"
    boolean: "BOOLEAN"
    java.lang.Float: "REAL"
    int: "INTEGER"
    java.lang.Boolean: "BOOLEAN"
    float: "REAL"
  autoIncrement: "PRIMARY KEY AUTOINCREMENT"
  orderDesc: "ORDER BY %order% DESC"
  orderAsc: "ORDER BY %order% ASC"
  limit: "LIMIT %limit%"
driverName: "MYSQL"
host: "database.originalnetwork-panel.dev"
database: "new_panel"
username: "root"
password: "EJNPZvmyYxkYwzPe7vCKkC7q6x4PRHfb"
port: 3306
useSSL: false